export type CardsByCategory = {
    [category: string]: string[];
  };
  
  export const cardsByCategory: CardsByCategory = {
    "Getting to Know Each Other": [
      "What's your full name, and is there a story behind it?",
      "Where did you grow up, and what was it like?",
      "How would your friends describe you in three words?",
      "What's the best advice you've ever received?",
      "What's your favourite family tradition?",
      "Do you prefer mornings or nights? Why?",
      "How do you like to spend your weekends?",
      "What's something that always makes you laugh?",
      "Have you ever met anyone famous?",
      "What's one thing on your bucket list?",
      "Do you prefer a big group of friends or a small, tight-knit group?",
      "If you could switch lives with someone for a day, who would it be and why?",
      "What's something people often misunderstand about you?",
      "If you could have dinner with any historical figure, who would it be?",
      "How do you handle stress or difficult situations?",
      "What’s your favourite holiday and why?",
      "Do you have any unusual or hidden talents?",
      "What’s the most embarrassing thing that’s ever happened to you?",
      "If you could instantly master any skill, what would it be?",
      "Do you believe in love at first sight?",
      "What’s your idea of a perfect day?",
      "What was the most rebellious thing you did as a teenager?",
      "What’s your most treasured possession and why?",
      "What’s the last book you read and enjoyed?",
      "What’s your favourite childhood memory?",
      "Who’s your role model in life?",
      "What would you do if you won the lottery?",
      "Do you prefer cats, dogs, or something else as pets?",
      "If you could travel anywhere in the world, where would you go?",
      "What’s one thing you’ve always wanted to try but never have?",
      "What’s your go-to karaoke song?",
      "If you could change one thing about the world, what would it be?",
      "Do you like surprises, or do you prefer things to be planned?",
      "What’s your guilty pleasure?",
      "If you could relive one day from your life, which would it be and why?",
      "Are you a collector of anything?",
      "What’s your favourite season and why?",
      "If you could have any job for a day, what would it be?",
      "What’s the best vacation you’ve ever had?",
      "Do you believe in fate or do you think we make our own destiny?",
      "If you could time travel, would you go to the past or the future?",
      "What’s your favourite type of music?",
      "What’s the most adventurous thing you’ve ever done?",
      "Have you ever been in a situation that completely changed your perspective on life?",
      "What’s something that inspires you?",
      "What’s your most memorable school experience?",
      "Who in your life has had the biggest impact on you?",
      "How do you feel about public speaking?",
      "If you could live in any historical era, when would it be and why?",
      "What’s your definition of success?",
    ],
    "Hobbies and Interests": [
      "What’s your favourite hobby, and how did you get into it?",
      "Do you have any hobbies you’re really passionate about?",
      "What’s the most recent hobby you’ve picked up?",
      "Do you prefer solo hobbies or group activities?",
      "What’s your favourite way to unwind after a busy day?",
      "Are you into arts and crafts? What have you made recently?",
      "What’s your favourite sport to play or watch?",
      "Do you enjoy cooking or baking? What’s your signature dish?",
      "What was the last thing you made with your hands?",
      "Do you like DIY projects or prefer buying things already made?",
      "What’s one hobby you’ve always wanted to try?",
      "Are you into photography or videography? What’s your camera of choice?",
      "What’s your favourite outdoor activity?",
      "Do you enjoy puzzles or brain teasers?",
      "How do you feel about reading? What’s the last book you enjoyed?",
      "Do you prefer fiction or non-fiction?",
      "What’s your favourite genre of music to listen to while working or relaxing?",
      "What’s a hobby you’ve abandoned and would like to revisit?",
      "Do you like playing video games? What’s your favourite game?",
      "Do you enjoy gardening or growing your own food?",
      "What’s your favourite type of exercise or fitness routine?",
      "Do you enjoy hiking or being in nature?",
      "Are you a collector? What do you collect?",
      "Do you enjoy watching movies or TV shows? What’s your go-to genre?",
      "Do you have any creative hobbies, like drawing, writing, or painting?",
      "What’s your favourite board game or card game to play with friends?",
      "Do you have a talent for something you don’t usually share with others?",
      "Do you prefer being active or relaxing on weekends?",
      "What’s your favourite social media platform and why?",
      "Do you like to spend your free time at home or out and about?",
      "Are you interested in fashion or keeping up with trends?",
      "Do you enjoy attending concerts or live events?",
      "What’s your favourite type of workout or fitness activity?",
      "Do you like spending time at a beach or in the mountains more?",
      "What’s the best hobby to do with friends?",
      "Do you play any musical instruments?",
      "What’s the best way for you to clear your mind?",
      "Do you enjoy attending workshops or classes to learn new skills?",
      "What hobby would you take up if time and money were no object?",
      "Do you like watching sports? If so, which one?",
      "Do you enjoy spending time on your own or with a group of people more?",
      "Are you into comic books or graphic novels?",
      "How do you feel about trying new things on a whim?",
      "What’s something you used to do but haven’t in a long time?",
      "Do you like watching documentaries? What’s your favourite topic?",
      "Are you interested in history or archaeology?",
      "Do you enjoy traveling to new places for your hobbies (e.g., art exhibitions, concerts)?",
      "Do you like being involved in creative communities, like online forums or groups?",
      "Do you enjoy playing sports or prefer watching them?",
      "What’s a hobby that makes you feel most alive?",
    ],
    "Travel and Adventure": [
      "What’s the best place you’ve ever visited?",
      "Where’s the next place you want to travel to?",
      "Do you prefer a beach holiday or a city break?",
      "What’s your most memorable travel experience?",
      "Have you ever traveled solo? How was it?",
      "What’s the longest trip you’ve ever been on?",
      "What’s your favourite country you’ve visited?",
      "If you could move to another country, where would it be?",
      "What’s the most spontaneous trip you’ve ever taken?",
      "Have you ever been on a road trip? Where did you go?",
      "What’s the best city you’ve visited for food?",
      "Do you prefer traveling by car, plane, or train?",
      "What’s the best adventure activity you’ve done?",
      "Have you ever had a travel disaster? What happened?",
      "What’s your dream vacation?",
      "Do you like traveling to touristy spots or off-the-beaten-path locations?",
      "What’s your favourite type of accommodation (hotel, hostel, Airbnb)?",
      "What’s the most beautiful place you’ve visited?",
      "If you could visit one place in the world, where would it be and why?",
      "Do you like to travel light or pack everything you might need?",
      "What’s your favourite type of transportation when traveling?",
      "Have you ever been on a cruise? Would you recommend it?",
      "What’s the weirdest food you’ve tried while traveling?",
      "What’s the best beach you’ve visited?",
      "Do you prefer exploring nature or experiencing the culture of a city?",
      "Have you ever traveled somewhere just to try a specific food?",
      "What’s the most interesting historical site you’ve visited?",
      "Do you prefer mountains, forests, or beaches for adventure trips?",
      "What’s the most unique experience you’ve had while traveling?",
      "Would you prefer to travel for leisure or for work?",
      "What’s the most remote place you’ve ever visited?",
      "What’s your favourite thing to do when you travel (e.g., sightseeing, hiking)?",
      "Have you ever been on a backpacking trip? Where did you go?",
      "What’s the most luxurious trip you’ve ever taken?",
      "What’s one place you’d recommend everyone should visit at least once in their life?",
      "Do you have any funny or embarrassing travel stories?",
      "Would you rather visit a new country or return to a place you’ve already been?",
      "What’s the best way to immerse yourself in a new culture when you travel?",
      "What’s the craziest thing you’ve done while on vacation?",
      "What’s the most adventurous activity you’d like to try?",
      "Do you prefer traveling in a group or alone?",
      "Have you ever made a lifelong friend while traveling?",
      "Do you prefer to stay in touristy areas or find hidden gems?",
      "What’s the best souvenir you’ve brought home from a trip?",
      "What’s your favourite airport or travel hub?",
      "Do you have a bucket list of destinations?",
      "Would you rather visit a place with historical significance or a relaxing getaway?",
      "What’s the longest time you’ve spent away from home?",
      "Do you prefer going to places that are hot or cold?",
      "What’s the one country you want to explore the most?",
    ],
    "Deep Conversations": [
      "What’s your biggest fear in life?",
      "Do you believe in destiny or free will?",
      "What’s your biggest regret?",
      "How do you define true happiness?",
      "What’s the most meaningful experience you’ve had?",
      "What’s one thing you’d change about yourself?",
      "What does success mean to you?",
      "Do you believe in life after death?",
      "What’s one thing you want to accomplish before you die?",
      "How do you handle failure?",
      "What’s your greatest strength and weakness?",
      "How do you deal with disappointment?",
      "What makes a person truly beautiful?",
      "Do you believe in love at first sight?",
      "What’s the most important lesson life has taught you?",
      "What would you do if you knew you had only a year to live?",
      "How do you want to be remembered?",
      "What’s the greatest act of kindness you’ve experienced?",
      "Do you think people can change, or is their nature fixed?",
      "What’s the best way to make the world a better place?",
      "What does friendship mean to you?",
      "What’s something you wish more people understood about you?",
      "What’s the one thing you cannot live without?",
      "What’s the most challenging thing you’ve ever done?",
      "Do you believe in fate or that we create our own future?",
      "What’s the biggest challenge you’re facing right now?",
      "What does love mean to you?",
      "What do you want to be remembered for?",
      "How do you cope with loneliness?",
      "What’s something you’d do differently if you could go back in time?",
      "What’s the most valuable thing you’ve learned from relationships?",
      "How do you feel about your own mortality?",
      "Do you think we are all connected in some way?",
      "What do you think happens after we die?",
      "What’s the most courageous thing you’ve ever done?",
      "What do you think is the key to a long-lasting relationship?",
      "What’s the biggest sacrifice you’ve made?",
      "What’s the most important quality you look for in a friend?",
      "What do you want to achieve in the next year?",
      "Do you believe people are inherently good or bad?",
      "What’s your opinion on the concept of soulmates?",
      "How do you define emotional intimacy?",
      "What’s your greatest hope for the future?",
      "What does it mean to be truly vulnerable?",
      "What’s one question you’ve always wanted to ask someone but haven’t yet?",
      "What’s the most valuable piece of advice you’ve ever given?",
      "How would you describe your relationship with yourself?",
      "What do you think it takes to live a fulfilled life?",
      "What does spiritual growth mean to you?",
      "What’s the hardest truth you’ve had to accept?",
    ],
  };
  